name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set lowercase repository owner
        run: echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${REPO_OWNER}/mi-app-nextjs:latest .
          docker tag ghcr.io/${REPO_OWNER}/mi-app-nextjs:latest ghcr.io/${REPO_OWNER}/mi-app-nextjs:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${REPO_OWNER}/mi-app-nextjs:latest
          docker push ghcr.io/${REPO_OWNER}/mi-app-nextjs:${{ github.sha }}
