name: Run Tests on Pull Request

# Se ejecuta en cada PR hacia cualquier rama
on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"  # Puedes poner la versión que uses en local

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Ejecutar tests con Vitest
      - name: Run tests
        run: npm run test
